'use client'

import type { Metadata } from "next";
import "./globals.css";
import { Inter } from 'next/font/google'
import { useUserStore } from "@/store/useUserStore";
import { useEffect } from "react";

const inter = Inter({
	subsets: ['latin'],
	display: 'swap',
})

// export const metadata: Metadata = {
// 	title: "Todo List",
// 	description: "Generated by create next app",
// };

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const isUserLogged = useUserStore((state) => state.initializeUser)

	useEffect(() => {
		isUserLogged()
	}, [])
	
	return (
		<html lang="en">
			<body className={inter.className}>
				{children}
			</body>
		</html>
	);
}
